<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit280407cc085ff1dc095fdf8ff7eb7a2f
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TelegramBot\\Api\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TelegramBot\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/telegram-bot/api/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit280407cc085ff1dc095fdf8ff7eb7a2f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit280407cc085ff1dc095fdf8ff7eb7a2f::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
